spring.datasource.url=jdbc:mysql://localhost:3306/rickmorty
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

rickmorty.api.url=https://rickandmortyapi.com/api/character

